autoload:
  querypath:
    path:           %SF_PLUGINS_DIR%/sfAltumoPlugin/lib/vendor/querypath/src
    recursive:      on
  twilio:
    path:           %SF_PLUGINS_DIR%/sfAltumoPlugin/lib/vendor/twilio/Services
    recursive:      on